### ISSUE TITLE
Invalid or not updated documentation

### ISSUE THREAD

**Issue by shaunkawano** [GoogleChrome/custom-tabs-client#13]
The sample code on [ Optimization Section](https://github.com/GoogleChrome/custom-tabs-client#optimization) is invalid or not updated. Specifically, `onServiceDisconnected` method is missing and `onCustomTabsServiceConnected` method is duplicated; the real one looks like this:
```java
CustomTabsClient.bindCustomTabsService(this, packageName,
        new CustomTabsServiceConnection() {
            @Override
            public void onCustomTabsServiceConnected(final ComponentName componentName,
                    final CustomTabsClient customTabsClient) {

            }

            @Override
            public void onServiceDisconnected(final ComponentName name) {

            }
        });
```

**UPDATED**

Also, the first parameter of `mayLaunchUrl()` has to be `Uri` object, and yet the sample code passes `String`, which is not correct.

The real signature of `mayLaunchUrl` is below:

```java
public boolean mayLaunchUrl(Uri url, Bundle extras, List<Bundle> otherLikelyBundles)
```

**Comment by pasko** [comment]
this should be done now, thanks for reporting
