### ISSUE TITLE
How to monitor the URL change in Custom Tabs?

### ISSUE THREAD

**Issue by changchingchi** [GoogleChrome/custom-tabs-client#17]
Can you provide a piece of sample code of how to monitor url changes in custom tabs? 
when the user init custom tab like this
` customTabsIntent.intent.setPackage(packageName);`
           ` customTabsIntent.launchUrl(activity, uri);`
`launchUrl` takes uri and fire the `activity` based on what we set up in `intent.setData(uri)`. like this, 

    public void launchUrl(Activity context, Uri url) {
        intent.setData(url);
        if (startAnimationBundle != null){
            context.startActivity(intent, startAnimationBundle);
        } else {
            context.startActivity(intent);
        }
    }
But how can we monitor the url changes in custom tabs?

**Comment by andreban** [comment]
You need to add a CustomTabsCallback when creating a new session. 

Modify the `CustomTabActivityHelper` class to add a CustomTabsCallback

```java
private CustomTabsCallback mCustomTabsCallback;

public void setCustomTabsCallback(CustomTabsCallback customTabsCallback) {
    mCustomTabsCallback = customTabsCallback;
}
```
Now, update the getSession method to pass the callback when creating a navigation session.
```java
public CustomTabsSession getSession() {
    if (mClient == null) {
        mCustomTabsSession = null;
    } else if (mCustomTabsSession == null) {
        mCustomTabsSession = mClient.newSession(mCustomTabsCallback);
    }
    return mCustomTabsSession;
}
```
You will then get callbacks that will report the user navigation. Note that you will not receive the Url the user navigated to, for privacy reasons.

**Comment by changchingchi** [comment]
Thanks for the reply @andreban, If we cannot check the url changes in custom tabs, then how can we make sure we redirect user back to our native app once user finishes a certain event such a log in, checkout, transaction payment? 

I have try to use `OnNavigationEvent` to monitor event, i only obtain some static `int` back indicating as "finish loaded", "start loading"..such a generic event only, which cannot help me distinguish user's behavior.

**Comment by andreban** [comment]
If you control the server side, you can create a custom scheme, such as `myapp://path/to/callback`, in your Android application, adding it as with an Intent Filter to the Activity the will handle the user after the transaction, and them have the server redirect the user to that custom scheme when the transaction is finished. Chrome will start the activity that responds to that scheme when the user is redirected.

**Comment by changchingchi** [comment]
@andreban I dont have the ability to control server. In this case all i know is once they finish the transaction, the page's url will be changed to a certain format, that is the main reason i want to detect the url change only.

**Comment by dmvjs** [comment]
In olden times the custom scheme would redirect from Chrome back to the app (assuming it was registered to the scheme) but new changes in Chromium appear to prevent this from happening without a `user gesture`. Are there plans for this Custom Tab implementation to allow or disallow for this sort of communication with the host app? User gesture appears to be required for now.
https://paul.kinlan.me/deep-app-linking-on-android-and-chrome/

**Comment by pasko** [comment]
closing, please continue at: https://code.google.com/p/chromium/issues/detail?id=543542
