### ISSUE TITLE
Is there an example app?

### ISSUE THREAD

**Issue by erlend-sh** [GoogleChrome/custom-tabs-client#18]
I'd really like to see Chrome Custom Tabs in action. Is there a an example app available for demoing purposes?

**Comment by changchingchi** [comment]
isn't this the github for the sample app?

**Comment by erlend-sh** [comment]
Sorry, I should have specified: Is the example app available for download / in the Play Store?

**Comment by pasko** [comment]
Valid request. Closed in favor of: https://code.google.com/p/chromium/issues/detail?id=541600
