### ISSUE TITLE
Exit animations on Marshmallow

### ISSUE THREAD

**Issue by greenfrvr** [GoogleChrome/custom-tabs-client#19]
I have tried custom tabs on Marshmallow (factory image for Nexus 5 build MRA58K) and found that exit animations don't work. Looks like on Marshmallow activity default exit animations are used. It seems that on 6.0 activity doesn't extract animation from bundle or does it incorrectly.

**Comment by pasko** [comment]
we don't frequently look at the github issue tracker, sorry, please continue here: https://code.google.com/p/chromium/issues/detail?id=543544
