### ISSUE TITLE
Header parameters

### ISSUE THREAD

**Issue by dmacan23** [GoogleChrome/custom-tabs-client#20]
Is there any way that I can put header data into request? I would like to access private page that requires user token. I have the token within my app, but how can I pass it to Chrome?

**Comment by pasko** [comment]
There is no way to do it at the moment other than via a server-side redirect. What is your usecase?

**Comment by idanakav** [comment]
joining the request, my use case is just to add a referer header
the WebView had a simple way to add it via:
```
loadUrl(String url, Map<String, String> additionalHttpHeaders) 
```

**Comment by pasko** [comment]
we do not look at the github issue tracker frequently enough, let's continue here:
https://code.google.com/p/chromium/issues/detail?id=543545
