### ISSUE TITLE
Is it possible to know if Chrome-tabs is available? 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [GoogleChrome/custom-tabs-client#21]
and if not, use a WebView instead?
Users might not have the latest version of Android/Chrome, and might not even have Chrome installed, so I'd like to use a Webview in all cases that Chrome-Tabs cannot work.

Is it possible?

**Comment by andreban** [comment]
Yes, it is possible. 

Check the [ServiceConnectionActivity.java](https://github.com/GoogleChrome/custom-tabs-client/blob/master/demos/src/main/java/org/chromium/customtabsdemos/ServiceConnectionActivity.java) for an example. It uses [WebviewActivity.java](https://github.com/GoogleChrome/custom-tabs-client/blob/master/demos/src/main/java/org/chromium/customtabsdemos/WebviewActivity.java) as a fallback, which is an Activity with a WebView.

**Comment by AndroidDeveloperLB** [comment]
Nice. Say, if I call the warmup() and/or mayLaunchUrl() , would it also help if I do it on a previous activity, before starting the new one?

Also, why doesn't the SDK also include the WebView fallback itself, so that it will look about the same on all possible states ?

**Comment by AndroidDeveloperLB** [comment]
Is it also always better to call the warmup() and mayLaunchUrl()  functions?
Sometimes (or even usually) I don't see much of a difference between using them and not using them...

**Comment by AndroidDeveloperLB** [comment]
I've tried to set minSdkVersion to 14, but the "com.android.support:customtabs" library doesn't allow me to do this. How come? I can use the WebView in case it's not available, anyway...

**Comment by pasko** [comment]
we do not look at github issues frequently enough, so let's continue this discussion here:
https://code.google.com/p/chromium/issues/detail?id=543546

We are tracking all customtabs related bugs in chromium issue tracker at the moment. This includes examples in this repo, chrome implementation and related android support library issues.

**Comment by AndroidDeveloperLB** [comment]
Too bad. Github is an awesome place to share code and also talk about it.
Also, this post was more of questions than an issue to report about .
