### ISSUE TITLE
Bug: library doesn't allow to use minSdkVersion to be 14

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [GoogleChrome/custom-tabs-client#22]
I've tried to set minSdkVersion to 14, but the "com.android.support:customtabs" library doesn't allow me to do this:

    Error:Execution failed for task ':demos:processDebugManifest'.
    > Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [com.android.support:customtabs:23.0.1] C:\Users\user\AndroidStudioProjects\custom-tabs-client\demos\build\intermediates\exploded-aar\com.android.support\customtabs\23.0.1\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="android.support.customtabs" to force usage

 How come? I can use the WebView in case it's not available, anyway...

**Comment by idanakav** [comment]
the customtabs library has minSdkVersion 15 (or even 16 on this repo).
the fix is pretty straight forward like suggested in your error:

```
   <uses-sdk
        android:minSdkVersion="14"
        android:targetSdkVersion="23"
        tools:overrideLibrary="android.support.customtabs"
        />
```

then in runtime just check whether the sdk version is lower than 15 and if so just use the WebView

**Comment by AndroidDeveloperLB** [comment]
Why is it set this way? we can check for the version, and use a WebView if needed...
Also, in which file should I put this ? It looks like a manifest instead of a gradle file... Isn't it a weird thing to do ? To put the same number on both the gradle file and the manifest?

**Comment by AndroidDeveloperLB** [comment]
I tried asking for a change of the library here:
https://code.google.com/p/android/issues/detail?id=189937
But they say I should report here, yet here you say that it's not related, as it's a sample, and that if I want, I can change the manifest. 
Please have a clear way to report things. It's very annoying that we can't report things about every thing that Google creates.

**Comment by pasko** [comment]
We have a way to report bugs, but it's not very clear by being at the end of the README.md. Sorry about that :)

I copied your bug to where we can actually track it:
https://code.google.com/p/chromium/issues/detail?id=543521

**Comment by AndroidDeveloperLB** [comment]
@pasko Chromium? But the bug is on a library that's for Android...
It's not even a bug on the Chrome app itself. More on the library that's provided via gradle...

It's not the first time I see that I can't find the correct place to report issues (example: play services) and ask for suggestions. Please do consider having a global website for all of Google's products.
