### ISSUE TITLE
ChromeConnectionService not found

### ISSUE THREAD

**Issue by nolanlawson** [GoogleChrome/custom-tabs-client#3]
I tried installing this on a variety of devices (from 4.3 to 5.1), but unfortunately when I launch it and tap the "Warmup Chrome" button, I get the error:

```
Unable to start service Intent { cmp=com.chrome.dev/org.chromium.chrome.browser.hosted.
                               ChromeConnectionService } U=0: not found
```

The other buttons don't do anything. I take it I need to wait for the next version of Chrome to be published to the store? I have Chrome Beta and the Beta Channel WebView installed as well. Regular Chrome version installed is 42.0.2311.111.

**Comment by pasko** [comment]
At the moment Custom Tabs are only available in the dev channel, please install it and try again.

Chrome Dev on Play:
https://play.google.com/store/apps/details?id=com.chrome.dev
