### ISSUE TITLE
Chrome custom tabs shares cookies, without protection

### ISSUE THREAD

**Issue by contactsunilkumar** [GoogleChrome/custom-tabs-client#8]
Am not sure if this issue is directly related to this post, but would like to understand the protection of browser cookie available through chrome custom tabs.
Since the browser cookies are available to the apps as well through custom tabs, so its easy to impersonate and get the access to the resources using shared cookies.

**Comment by pasko** [comment]
Custom Tabs were designed *not* to share cookies with apps for the reason you are describing. If you found a way for apps to access custom abs cookies, please report them using this template:
https://code.google.com/p/chromium/issues/entry?template=Security%20Bug
